#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

mkdir -p output
chmod -R +w output

USE_BINARY_MASK=$(jq -r .use_binary_mask config.json)

if $USE_BINARY_MASK
then
    USE_BINARY_MASK="--use_binary_mask"
else
    USE_BINARY_MASK=""
fi

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_track_local \
    --force \
    --out_dir output \
    --out_tractogram track.trk \
    $USE_BINARY_MASK \
    --stopping_thr $(jq -r .stopping_thr config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --step_size $(jq -r .step_size config.json) \
    --tracking_method $(jq -r .tracking_method config.json) \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    $(jq -r .peaks config.json) $(jq -r .stopping_files config.json) \
    $(jq -r .seeding_files config.json)

echo "done"
