#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

set -e
set -x

cmd=`jq -r .command config.json`
case "$cmd" in

    dipy_track_local:eudx)
        cat > script.sh <<EOF
#!/bin/bash
dipy_mask --force \
    --use_binary_mask $(jq -r .use_binary_mask config.json) \
    --stopping_thr $(jq -r .stopping_thr config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --step_size $(jq -r .step_size config.json) \
    --tracking_method "eudx" \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    $(jq -r .peaks config.json) $(jq -r .stopping_files config.json) $(jq -r .seeding_files config.json)
EOF
      ;;
    dipy_track_local:det)
        cat > script.sh <<EOF
#!/bin/bash
dipy_mask --force \
    --use_binary_mask $(jq -r .use_binary_mask config.json) \
    --stopping_thr $(jq -r .stopping_thr config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --step_size $(jq -r .step_size config.json) \
    --tracking_method "det" \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    $(jq -r .peaks config.json) $(jq -r .stopping_files config.json) $(jq -r .seeding_files config.json)
EOF
        ;;
    dipy_track_local:prob)
        cat > script.sh <<EOF
#!/bin/bash
dipy_mask --force \
    --use_binary_mask $(jq -r .use_binary_mask config.json) \
    --stopping_thr $(jq -r .stopping_thr config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --step_size $(jq -r .step_size config.json) \
    --tracking_method "prob" \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    $(jq -r .peaks config.json) $(jq -r .stopping_files config.json) $(jq -r .seeding_files config.json)
EOF
    dipy_track_local:cp)
        cat > script.sh <<EOF
#!/bin/bash
dipy_mask --force \
    --use_binary_mask $(jq -r .use_binary_mask config.json) \
    --stopping_thr $(jq -r .stopping_thr config.json) \
    --seed_density $(jq -r .seed_density config.json) \
    --step_size $(jq -r .step_size config.json) \
    --tracking_method "cp" \
    --pmf_threshold $(jq -r .pmf_threshold config.json) \
    --max_angle $(jq -r .max_angle config.json) \
    $(jq -r .peaks config.json) $(jq -r .stopping_files config.json) $(jq -r .seeding_files config.json)
EOF
        ;;
    *)
        echo "invalid command: $cmd"
        exit 1
esac

chmod +x script.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:1.1.1 ./script.sh

echo "done"